---
- hosts: foohost.foo.com
  roles:
    - linux-system-roles.certificate
  vars:
    certificate_requests:
      - name: "{{ ansible_hostname }}"
        dns: "{{ ansible_fqdn }}"
        principal: "HTTP/{{ ansible_fqdn }}@FOO.COM"
        ca: ipa
